AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for Lambda invoked by Amazon Connect querying DynamoDB

Parameters:
  InstanceArn:
    Type: String
    Description: The ARN of your Amazon Connect instance that will invoke the Lambda Function
  
Resources:
  MyLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MyLambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBQueryPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                Resource: !GetAtt MyDynamoDBTable.Arn

  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: MyConnectLambda
      Runtime: python3.14
      Handler: index.lambda_handler
      Role: !GetAtt MyLambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import boto3
          import os

          dynamodb = boto3.resource('dynamodb')
          table_name = os.environ['DYNAMODB_TABLE_NAME']
          table = dynamodb.Table(table_name)

          def lambda_handler(event, context):
              print(f"Recieved event from Connect: {event}")
              
              # Get dialled phone number from information passed to Lambda by Connect
              phone_number = event['Details']['ContactData']['SystemEndpoint']['Address']

              # Make request to DynamoDB
              response = table.get_item(Key={'telephone-number': phone_number})

              # Get result of request
              item = response.get('Item', {})

              print(f"Retrieved item from DynamoDB: {item}")

              # Return attributes back to Connect
              return item
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref MyDynamoDBTable

  MyLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${MyLambdaFunction}
      RetentionInDays: 14

  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: MyDynamoDBTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: telephone-number
          AttributeType: S
      KeySchema:
        - AttributeName: telephone-number
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  MyConnectLambdaIntegration:
    Type: AWS::Connect::IntegrationAssociation
    Properties:
      InstanceId: !Ref InstanceArn
      IntegrationType: LAMBDA_FUNCTION
      IntegrationArn: !GetAtt MyLambdaFunction.Arn